# The URL the site will be built for
base_url = "https://icancodeclub.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "iCanCode Club"

[extra]
email = "info@icancodeclub.com"
phone = "(585) 434-5533"

# social media icons for the footer
[[extra.social]]
    name = "Twitter"
    icon = "/icons/twitter.png"
    url = "https://twitter.com/iCanCodeClub"
[[extra.social]]
    name = "Facebook"
    icon = "/icons/facebook.png"
    url = "https://www.facebook.com/pages/ICanCode/942981635784038"
[[extra.social]]
    name = "LinkedIn"
    icon = "/icons/linkedin.png"
    url = "https://www.linkedin.com/pub/icancode-kids-club/101/9b7/6b1"

# partnership icons for the footer
[[extra.partners]]
    name = "Town of Perinton"
    icon = "/icons/perinton.jpg"
[[extra.partners]]
    name = "Brighton Community Education"
    icon = "/icons/brighton.jpg"